In [4]:
# Import TF 2.X and make sure we're running eager.
import tensorflow as tf
assert tf.executing_eagerly()

In [5]:
import tensorflow_hub as hub
import numpy as np

In [6]:
# Load the module and run inference.
module = hub.load('https://tfhub.dev/google/nonsemantic-speech-benchmark/trill-distilled/2')

2023-05-12 11:42:52.851624: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-12 11:42:52.853015: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [7]:
wav_as_float_or_int16 = np.sin(np.linspace(-np.pi, np.pi, 128), dtype=np.float32)

In [9]:
import librosa
y, sr = librosa.load('/media/emile/disk/Chatbot_10_15/USER_01_CB2_00_00.wav', sr=16000)

In [10]:
y

array([0.04076386, 0.07565035, 0.09392864, ..., 0.        , 0.        ,
       0.        ], dtype=float32)

In [11]:
emb = module(samples=y, sample_rate=16000)['embedding']
# `emb` is a [time, feature_dim] Tensor.
emb.shape.assert_is_compatible_with([None, 2048])

In [17]:
# print(emb)
import pandas as pd

pd.DataFrame(emb.numpy())
# emb.numpy()

0         1         2         3         4         5         6     \
0   0.337506 -0.040675  0.080816  0.088913  0.147161  0.321658  0.258711   
1   0.122066  0.174515  0.323350  0.372318  0.106595  0.511789  0.276275   
2   0.102713  0.282442  0.416054  0.706489  0.224125  0.040456  0.179622   
3   0.038816 -0.045828  0.168345  0.485001  0.390206 -0.079251  0.245818   
4   0.159759  0.087066  0.219032  0.126468  0.451057  0.175705  0.082451   
..       ...       ...       ...       ...       ...       ...       ...   
74  0.164002  0.125804  0.147179 -0.025500 -0.041062  0.351944  0.658185   
75  0.144374  0.296652  0.199200  0.301183  0.267612  0.369479  0.241292   
76  0.001786  0.351002  0.223638  0.333136  0.488250  0.256204  0.013433   
77  0.090239  0.138538  0.097028  0.389385  0.470858 -0.134868  0.185367   
78  0.117401  0.129924  0.037877  0.212045  0.278560 -0.045290  0.052637   

        7         8         9     ...      2038      2039      2040      2041  \
0   0.262652  0.050555  0.434577  ...  0.106480  0.184365  0.355496  0.100770   
1   0.705499  0.256095  0.225592  ... -0.196828  0.587497  0.108741  0.274103   
2   0.166533  0.048880  0.277912  ...  0.128521  0.492704  0.276728  0.088314   
3   0.226432  0.383727  0.344295  ...  0.424098  0.288179  0.293488  0.355201   
4   0.141692  0.411304  0.419022  ...  0.296449  0.041784  0.246841  0.166529   
..       ...       ...       ...  ...       ...       ...       ...       ...   
74  0.287136  0.164369  0.097967  ...  0.157654  0.215302  0.398865 -0.214418   
75  0.082927  0.078578  0.000010  ...  0.232222  0.111789  0.183152  0.086149   
76  0.326276  0.043618  0.375454  ...  0.324294  0.077265  0.199864  0.295231   
77  0.226538  0.027415  0.277127  ...  0.260614  0.196878  0.309701  0.424242   
78  0.224551 -0.047306  0.094918  ...  0.276126  0.156459  0.295758  0.268446   

        2042      2043      2044      2045      2046      2047  
0   0.168504  0.167772  0.072285  0.403610  0.178494  0.528386  
1   0.132199  0.165451  0.232621  0.509083  0.169190  0.138179  
2   0.475909  0.065890  0.408152  0.698953  0.366564  0.065407  
3   0.269071  0.266953  0.307074  0.524771  0.199257 -0.051795  
4   0.272051  0.182839  0.410285  0.312769  0.257206  0.484821  
..       ...       ...       ...       ...       ...       ...  
74 -0.119118 -0.001416  0.295848  0.418526  0.312677  0.374377  
75  0.483691  0.045824  0.372664  0.347135  0.391633  0.158330  
76  0.403349  0.245053  0.311306  0.289344  0.191157  0.228498  
77  0.313489  0.192337  0.183395  0.068969  0.114205  0.246835  
78  0.035386  0.045996  0.205074  0.033418  0.245389  0.287909  

[79 rows x 2048 columns]

In [19]:
audio_samples = tf.zeros([3, 64000])
audio_samples

<tf.Tensor: shape=(3, 64000), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [8]:
wav_as_float_or_int16

array([ 8.74227766e-08, -4.94537354e-02, -9.87865329e-02, -1.47877350e-01,
       -1.96606517e-01, -2.44854316e-01, -2.92503148e-01, -3.39435965e-01,
       -3.85538340e-01, -4.30697232e-01, -4.74801928e-01, -5.17744958e-01,
       -5.59420705e-01, -5.99727690e-01, -6.38566852e-01, -6.75843477e-01,
       -7.11466193e-01, -7.45347679e-01, -7.77405381e-01, -8.07560444e-01,
       -8.35739434e-01, -8.61873090e-01, -8.85897756e-01, -9.07754481e-01,
       -9.27389622e-01, -9.44755375e-01, -9.59809184e-01, -9.72514093e-01,
       -9.82839167e-01, -9.90759015e-01, -9.96254325e-01, -9.99311686e-01,
       -9.99923527e-01, -9.98088360e-01, -9.93810713e-01, -9.87101078e-01,
       -9.77975845e-01, -9.66457307e-01, -9.52573657e-01, -9.36358988e-01,
       -9.17852819e-01, -8.97100568e-01, -8.74152958e-01, -8.49066079e-01,
       -8.21901441e-01, -7.92725503e-01, -7.61609554e-01, -7.28629887e-01,
       -6.93867087e-01, -6.57406271e-01, -6.19336724e-01, -5.79751551e-01,
       -5.38747668e-01, -

In [1]:


import tensorflow_hub as hub
import numpy as np

# Load the module and run inference.
module = hub.load('https://tfhub.dev/google/nonsemantic-speech-benchmark/trill-distilled/2')
# `wav_as_float_or_int16` can be a numpy array or tf.Tensor of float type or
# int16. The sample rate must be 16kHz. Resample to this sample rate, if
# necessary.
wav_as_float_or_int16 = np.sin(np.linspace(-np.pi, np.pi, 128), dtype=np.float32)
emb = module(samples=wav_as_float_or_int16, sample_rate=16000)['embedding']
# `emb` is a [time, feature_dim] Tensor.
emb.shape.assert_is_compatible_with([None, 2048])

print(emb)


2023-05-12 11:36:56.287357: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


AttributeError: module 'tensorflow' has no attribute 'enable_v2_behavior'